apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: appexemplo
  labels:
    app: appexemplo
  namespace: app-py
spec:
  podMetricsEndpoints:
  - port: http
    interval: 10s
  selector:
    matchLabels:
      app: appexemplo